title: Linux 内核调度子系统 LKML 日报
description: 每日自动分析 kernel/sched/* 邮件列表
baseurl: "/lkm"
url: "https://1343503048.github.io"
markdown: kramdown

exclude:
  - references/
  - scripts/
  - sched/
  - Gemfile*
  - vendor/
  - node_modules/
  - _daily/
